# Generated by Django 4.2 on 2023-04-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_picture_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='RecipeStep',
        ),
    ]
